== L'amoureux déchu

[verse]
____
Je ne comprends pas
Pourquoi on ne m'enterre pas,
Moi qui n'aime plus
Depuis que je suis déchu.

Même la mort ne veut pas de ma carcasse,
Car je ne suis plus de la race
De ceux qui la fuient,
Ayant peur de l'éternelle nuit.

Je déteste le temps,
Il ne fait que retarder
Tout ce que je voudrais être l'aboutissement
D'une vie déjà délabrée.

La seule chose que je désire encore
C'est la présence d'une femme, le réconfort,
Me sentir aimé même aux portes de la mort.

J'ai, cependant, encore une chance d'être apprécié,
Ne serait-ce que lorsque mon âme m'aura quittée,
Par les vers qui dévoreront mon corps putréfié!

Consolez-vous,
Ce n'est pas votre manque de passion
Qui a fait que mon cœur n'est plus doux,
Mon amour pour vous était trop fou.
____
<<<
[verse]
____
Il ne me reste plus que le souvenir
De votre beau sourire,
C'est d'ailleurs ce qui me fait errer,
Mon esprit damné cherche à vous retrouver.

Je sais que je suis condamné,
Car de votre cœur si mystérieux,
Depuis longtemps je suis oublié,
Alors, je ne reverrai plus jamais les cieux.
____