== Chagrins refoulés

[verse]
____
Le Prince, mortellement blessé,
Son âme allait le quitter,
Sa cause était désespérée.

C'est alors qu'il aperçut une femme
Qui avec des cendres produisait une flamme.
Elle l'accueillit et en quelques temps, il reprit goût à la vie.
Se croyant guéri,
Il se promit que, bientôt, il quitterait son lit,
Et qu'un guerrier, il deviendrait,
Que plus jamais on ne le blesserait.

Malheureusement, il était moins sage
Que cette femme qui lui fit ses bandages
Car de sang, il fût bientôt couvert,
Son cœur était ouvert,
L'ennemi l'ayant attaqué par derrière.
Il aurait dû se méfier,
Il n'aurait pu en être autrement de ce chevalier
Appelé Passé.

Il tomba, croyant que tout était terminé,
Pourtant, il se réveilla, désorienté.
Il était mystérieusement arrivé auprès de cette dame
Qui tentait de le sauver du coup de la mortelle lame.

Cette fois, aidé de conseils éclairés,
Le Prince ne se releva pas après avoir cicatrisé,
Et de sagesse, il hérita de cette femme au passé tourmenté.
Bien qu'elle fût douceur et tendresse,
Son visage rayonnant cachait une insondable tristesse.
Avec le temps, il apprit à voir au-delà des illusions
Et il s'intéressa aux passions
De cette amie morte, alors qu'elle était enfant,
Tuée par l'homme méprisant.

Le Prince ne put que la consoler,
Car, il savait que ses rêves et ses passions, il ne pouvait les lui rapporter.
Bien souvent, il voulut la prendre dans ses bras
Pour lui montrer qu'il comprenait, mais la peur ne lui permit pas,
Le préservant ainsi de blesser son amie,
Ne voulant pas un jour se sentir haï.

Un beau matin, le Prince disparût
De la vie de la gente dame, avec seulement un bref salut.
Il fallait qu'il parte; menacé
Autant par sa peur que par le Passé
Sur sa trace, tous deux lancés.

Un jour, le Prince trouva la légendaire cuirasse,
Celle qui empêcherait qu'on le terrasse.
Ciselée dans un métal noir d'ébène,
Elle était l’obstacle à la peine.
Aux yeux de ses ennemis, elle était un hommage à la haine,
La vengeance étant sa reine.

Le Prince devint impitoyable,
Détruisant les sources de ses souffrances interminables,
Les chassant de son esprit
Pour qu'il puisse désormais savourer la vie.
C'est ainsi que Souvenir, fils du Passé et de la Peine,
Succomba sous les coups du Prince empli de haine.

Même champion indisputé,
Sous son casque, des larmes coulèrent,
Car, il comprit, qu'il y a des peines, des colères,
Qui ne peuvent être totalement éliminées
Parce que trop longtemps refoulées, sans pouvoir les exprimer.
____
