== La chanson de l'oublie

[verse]
____
Elle était la plus belle
J'aurais tout donné pour elle.
Même si j'étais malhabile,
Je croyais qu'avec elle ce serait facile.

Après deux années, un tas de vaisselle brisée,
J'ai fait mes bagages et je l'ai laissée.
J'étais écœuré d'être toujours le coupable,
D'être celui des deux qui est l'incapable.

À l'abri, avec mes p'tits, chez mon meilleur ami,
Je parlais d'elle comme d'une vieille ennemie.
À coup de jurons, je la rebaptisais,
Oubliant son nom et tout ce qu'elle m'apportait.

Il y a deux semaines, mon chum m'a dit:
"On va à la terrasse, il faut que tu l'oublies."
À la terrasse, assise juste en face,
Je vois le sosie de mon ancienne garce.

Ho non, je ne peux pas l'oublier
Son souvenir me suit, je suis enchaîné.
J'me demande ce que j'ai fait au ciel,
Pour que tout me rappelle le temps passé avec elle.



L'autre jour, elle me téléphone,
En me disant qu'elle s'ennuie de son homme.
Je lui ai dit:
"Ton homme est pas ici,
J'pense qu'il est en Abitibi!"

On s'est engueulé comme du poisson pourri,
À la façon d'autrefois, avant que ce soit fini.
J'ai raccroché ben en maudit,
Croyant que chez mon ami je serais à l'abri.

Il y a une semaine, mon chum m'a dit:
"On va au cinéma, il faut que tu l'oublies."
Au cinéma, c'est l'histoire d'un bon gars:
En voyant sa blonde, il ne se sauve pas!

Ho non, je ne peux pas l'oublier
Son souvenir me suit, je suis enchaîné.
J'me demande ce que j'ai fait au ciel
Pour que tout me rappelle le temps passé avec elle.

La fin de semaine dernière, je suis allé la voir,
M'apercevant que sans elle je broyais du noir.
Nous nous sommes parlé, on s'est expliqué,
On s'est embrassés et notre histoire a continué.

Elle est la plus belle
Je donnerais tout pour elle.
Même si je suis malhabile,
Je sais que l'amour n'est pas toujours facile.
____
