== Le cornichon superficiel

[verse]
____
Tu peux réinventer le monde
Avec des paroles que tu penses intellectuelles
Mais, je dois te dire que tu me fais honte:
Tu ne sacrifierais même pas ta vie artificielle
Pour sauver ton prochain d'un danger mortel.

Alors, je t'en prie, tais-toi au lieu de dire
Qu'à tous les maux tu as la solution d'avenir
À mes oreilles, tu es  bien pire!
Tu me donnes envie de vomir
Car tu as la capacité de défendre tes frères
Tu gaspilles cependant ton énergie à tout dire
Et à ne rien faire.

Intelligence et idiotie se côtoient en toi.
Tu ne peux garder tes commentaires,
Les empêcher de heurter ma foi,
En des efforts concrets pour sortir les gens du cimetière
Plutôt que de les enterrer sous des paroles éphémères.

Je rêve aussi d'un monde juste,
Mais  je me l'imagine, je me l'illustre,
Et cette idée me pousse vers ce rivage.
Tandis que toi, tu voudrais que les gens soient intégrés
À ton idiotie, à tes folies, pour flatter ta fierté démesurée.

Ne sais-tu pas encore
Que pour sortir quelqu'un d'une mare de boue,
Il faut plus que lui tendre la main en effort?
Tu dois te salir toi aussi pour le remettre debout!

Je t'en conjure, fait donc comme les autres de ta race,
Pousse tranquillement au lieu de laisser traîner ta langue fugace.
Sinon, Cornichon Superficiel, dans le potager je te replacerai à ta place!
____
