== Le cornichon superficiel

[verse]
____
Tu peux réinventer le monde
Avec des paroles que tu penses intellectuelles
Mais, je dois te dire que tu me fais honte:
Tu ne sacrifierais même pas ta vie artificielle
Pour sauver ton prochain d'un danger mortel.

Alors, je t'en prie, tais-toi au lieu de dire
Qu'à tous les maux tu as la solution d'avenir
À mes oreilles, tu es  bien pire!
Tu me donnes envie de vomir
Car tu as la capacité de défendre tes frères
Tu gaspilles cependant ton énergie à tout dire
Et à ne rien faire.

Intelligence et idiotie se côtoient en toi.
Tu ne peux garder tes commentaires,
Les empêcher de heurter ma foi,
En des efforts concrets, loin du cimetière,
De tes paroles éphémères.

Je rêve aussi d'un monde juste,
Mais  je me l'imagine, je me l'illustre,
Et cette idée me pousse vers ce rivage.
Tandis que tu voudrais que les gens s'intègrent
À ton idiotie, à tes folies, à ta fierté démesurée.


Ne sais-tu pas encore
Que pour sortir quelqu'un d'une mare de boue,
Il faut plus que lui tendre la main en effort?
Tu dois te salir toi aussi pour le remettre debout!

Fait donc comme les autres de ta race,
Pousse tranquillement,
Cesse de laisser traîner ta langue fugace.
Sinon, Cornichon Superficiel, dans un élan
Au potager je te remettrais à ta place!
____
