== La danse des disparus

[verse]
____
Le vent agite les inertes feuilles
Faisant virevolter du même coup le voile du deuil.
L'air frisquet danse avec la nuit,
Leur pas de deux égaie les ténèbres, chasse l'ennui.
Le lugubre couple remue les trépassés,
Narguant les grands frênes dénudés de leur verdure passée.
Le craquement des branches appelle en vain les enfants bien-aimés,
Ceux-là que l'automne a flétris et que l'hiver ne tardera pas à enterrer.
Les arbres, ces géants dégarnis, regrettent l'été
Maintenant que leur manteau vert est tombé.


La danse se fait envoûtante, appelant les disparus de son rythme effréné.
Aux feuilles se joignent bientôt les morceaux d'une lettre dont l'encre est délavée,
Les larmes ou la pluie ayant effacé les dernières traces d'un amour oublié.
La valse s'accélère alors qu'arrivent les objets utiles de naguère,
Abandonnés ou bien égarés, joyeux compères qui éloignent le silence austère.

Voilà de nouveau le cortège de novembre, dernier sursaut de vie,
Que la dame blanche couvrira prochainement d'un linceul gris.
____
