== Dénoncés

[verse]
____
Je sors du rang
Je refuse d'agir selon les règles du sang!
Femmes, je vous respecte
Pour ce que vous êtes
Et jamais le fait que je sois un mâle
Ne me fera vous faire du mal.

J'admire la force et la tendresse
Qui cohabite en chacune de vous.
Pour cela, je vous appelle déesses.
Force morale,
Que bien des hommes tuent
En vous faisant du mal.
Tendresse,
Que bien des hommes blessent.

Ceux-là, que je ne nommerai pas,
Ces idiots qui agissent comme des rats
Vermines à qui je souhaite de pourrir en enfer
Le nom d'homme, vous ne le méritez pas
Car il ne revient qu'à mes frères.
Mes frères,
Ces hommes qui honorent
Leur origine au lieu de la bafouer.
Ils vous élèvent de leurs paroles d'or
Au-dessus de cette mare grouillante
Où il n'y a que sexe et violence.
____
<<<
[verse]
____
Ils sont peu
Et c'est malheureux
À se battre pour vos yeux
Plutôt que pour leur queue...
Queue de rat
Que j'écraserais d'un pas!

Contre ces rats puants
Je jure, toute ma vie durant
De vous aider.
Je connais déjà trop de femmes
Qui se sont fait voler leur âme
Par ces petits êtres infâmes.
____
