== Désir funèbre

[verse]
____
Tu n'es plus avec moi,
Pour me réchauffer alors qu'il fait si froid.
Je t'en prie, reviens vers ton amoureux,
Regarde-moi dans les yeux, caresse mes cheveux.
Sauve-moi de la solitude, ce destin affreux.

Tu n'es plus là,
Pour me prendre dans tes bras,
Contre ton cœur, comme autrefois.
Je donnerais ma vie afin, qu'à la tombée de la nuit,
Tu trouves ton chemin jusqu'à ton amant endormi.
Viens, brise les limites de la  morne réalité,
Qu'une dernière fois nous échangions un baiser,
Oubliant le prix de ma témérité,
Tous deux de chair et de sang avant notre arrivée
À la porte de l'éternité.

Je suis seul sous la pluie avec mes rêves anéantis,
Les autres sont partis car ils te croient morte.
Ces idiots ne réalisent pas que tu n'es qu'endormie,
Même la mort ne peut te retenir, tu es trop forte!





La pluie s'ajoute à mes larmes.
Le ciel pleure aussi ma tendre bien-aimée,
Ma jeune femme adorée.
Les lugubres monuments de pierre se dressent
Tout autour de moi et de mon amour.
Ils me rappellent la morne réalité:
Même si les gens qu'ils laissent
Désirent leur retour
Ceux qui sont ici, y restent.
____
