== Désir funèbre

[verse]
____
Tu n'es plus avec moi,
Pour me réchauffer alors qu'il fait si froid.
Je t'en prie, reviens vers ton amoureux,
Regarde-moi dans les yeux, caresse mes cheveux.
Sauve-moi de la solitude, ce destin affreux.

Tu n'es plus avec moi,
Pour me prendre dans tes bras, contre ton cœur, comme autrefois.
Je donnerais ma vie afin, qu'à la tombée de la nuit,
Tu retrouves ton chemin jusqu'à ton amant endormi.
Viens, brise les limites imposées par la  morne réalité,
Qu'une dernière fois nous nous aimions, oubliant le prix de ma témérité,
Tous deux de chair et de sang avant notre arrivée à la porte de l'éternité.

Je suis seul sous la pluie, seul avec mes rêves anéantis,
Les autres sont partis car ils te croient morte.
Les idiots, ils ne peuvent réaliser que tu n'es qu'endormie,
Que même la mort ne peut te retenir, tu es trop forte!

La pluie s'ajoute à mes larmes.
Le ciel pleure aussi ma tendre bien-aimée, ma jeune femme.
Les lugubres monuments de pierre se dressent
Tout autour de moi et de mon amour.
Même si les gens qu'ils laissent désirent leur retour,
Avec tristesse, je m'aperçois que ceux qui sont ici, y restent.
____
