== Individuels

[verse]
____
Des entrailles de cette île d'acier et de béton
Surgit pareil à un démon
Cette créature irréaliste portant en elle,
Les fervents défenseurs de l'individualisme.

Avec un rugissement assourdissant
La bête s'arrête docilement,
Pour laisser partir ceux qui vont à la recherche
De leur précieux argent
Ignorant les pauvres qui leur tendent la perche.

Encore considéré comme un étranger
Je risque mon identité
En échange, d'un peu de connaissance,
Pénétrant au cœur de ce monstre de la démence
Qui se lance à la suite du temps
Aussi vite que le vent.
J'observe les gens de mes yeux,
Qui sont aussi vieux que mes souvenirs heureux,
En espérant trouver parmi eux
Une lueur dans le dédale de ces tunnels ténébreux.

Rien à faire, j'ai l'impression
D'avoir quitté la terre
Pour un sombre univers
Où on ignore ce qu'est la compassion.

Je crois être en enfer,
Lorsqu'une femme d'allure fière
Se fraie un chemin
Parmi ceux qu'on dit humains.
Son regard, pur comme le cristal, me transperce
Un instant avant que ne s'abatte la herse
Et que je ne disparaisse à toute vitesse,
Sur le dos de l'animal des bas-fonds terrestres.

C'est avec tristesse, mais sans aucune sagesse,
Que j'espère revoir cette éblouissante princesse.
Si inhabituelle dans le monde cruel
Des êtres individuels...
____
