== La porte

[verse]
____
Aujourd'hui cette porte s'ouvre
Sur le monde des adultes
Où il y a tant de choses qu'il faut que tu découvres.
Le peu de l'enfant qu'il restait en toi
Doit mourir avec l'âge car c'est la loi,
En ce monde, le temps est roi.

Des épreuves tu rencontreras,
Au-delà de cette porte,
Mais sur ta détermination,
Ils se lasseront,
Car elle sera forte.

Des joies, également,
Il y en aura
Mais aussi fragiles au vent
Que le plus coloré des cerfs-volants.

Alors, en ce jour de tes dix-huit ans,
Ne pense pas aux épreuves, ni aux cerfs-volants,
Et d'un bond,
Passes cette porte dont les gonds
Ne peuvent plus te retenir maintenant.




Si jamais tu tombes, ou même si debout tu te tiens,
Je serai là, prêt à te tendre la main,
Mais ce ne sera que demain.
Car, pour l'heure, je dois partir,
Mes promesses je ne saurais faire mentir.
Quand le besoin de ma présence
Se fera sentir
Alors, je pourrai t'aider de ma modeste science.

D'ici là, je te souhaite la bienvenue
Dans un monde où tu n'as encore rien vu
Car des gens, tu ne voyais pas encore
La conscience à nu.
____
