== La mort du poète

[verse]
____
Lorsque sa raison s'évanouit,
Que le désespoir l'envahit,
L'homme qui exprime sa douleur
Sur la page d'une cruelle blancheur
Cesse d'être lui-même, meurt.
L'ombre du disparu se dresse alors
Pour devenir de tous les maux le mentor.
Le poète naît ainsi mais n'apporte aucun réconfort,
Ne peut faire que du tort,
Aux amis du mort.

Le poète, de sa naissance à sa chute,
Dira, écrira que la vie est une constante lutte;
Il ne peut être s'il ne se fait pas maudire,
Tourmenté comme le premier des martyrs.

Nous pourrions croire, étant né de la désolation,
Que le bonheur le tuerait de consternation.
Cette abjecte créature, malheureusement,
Ne peut être éliminée aussi facilement.
La joie ne fera que nourrir son imagination,
Faisant surgir des pays mystérieux du cœur d'un lion.
Nouveau prince, d'un lieu où il y a encore tout à dévaster,
Il créera des champs de fleurs et une rose pour les voir se faner,
S'inventera une vaste épopée pour sa vie tenter d'expliquer.

Si beaux sont ses rêves,
Lui accordant une courte trêve,
Chassant un instant sa terrible destinée, qu'il ne peut oublier:
De l'ombre il est venu, à l'ombre il devra retourner.

Le poète ressentant sa fin arriver
Une hécatombe, en son monde, il tentera de créer
Pour avec lui entraîner l'esprit du damné
Qui, suite à sa disparition, devrait ressusciter.

Si l'homme n'est pas assez fort
Sur lui s'abattront le malheur et la mort,
Car le poète, même inhumé,
Son univers délabré continuera d'exister.

La conscience de son hôte sera éternellement hantée:
Le bonheur ni la haine il ne pourra désormais exprimer
Sans voir l’ombre du poète vers lui ramper.
____
