== Purgatoire

[verse]
____
L'ombre de ma vie m'a suivie
Même ici, je ne suis pas à l'abri
De ceux que j'ai détruits
Alors que je n'avais encore rien compris.
Je ne suis plus qu'un corps décrépit
Mais les souvenirs dans la mort m'ont suivi.
Au fond de cette fosse, je me décompose,
Sous la terre je me repose,
Attendant la métamorphose.
Lorsque mon cadavre ne sera que poussière,
N'étant plus matière, je quitterai cet enfer.

Au sein des ténèbres odieuses,
Je ne reste pas sourd aux lèvres hargneuses.
Je n'ai pas de répits
En ce lieu que je voulais être le paradis;
Pas assez élevé était mon esprit
Pour s'envoler hors de portée de mes ennemis.
Sur ma sépulture, on crache avec bassesse,
Ma stature n'est plus cachée par la richesse
D'un empire construit au coût de la tristesse.
____
<<<
[verse]
____
Chaque jour, mes yeux aveugles revoient ma vie,
Cette vision m'indique que je mérite d'être ici.
Je suis mieux dans ma tombe moisie
Qu'en une vie parmi le monde de l'hypocrisie,
Ce lieu où je croyais avoir tant d'amis.
Je me console car bientôt je partirai
Mes fautes étant expiées.

Des égoïstes, à ma suite, seront enterrés
Leur existence ils devront un jour regretter:
Devant leur misérable vie d'insensés
Ils seront confrontés, peut-être pour l'éternité.
____
