== Sentence

[verse]
____
Je t'accuse de m'avoir tué,
De m'avoir fait renier mon passé.
Tu es coupable,
Il n'y a personne d'autre qui soit capable
De m'avoir rendu aussi lamentable.

Lorsque, la nuit arrivée, je dormais,
De mon sommeil, tu profitais
Et je me réveillais complètement dérouté
Par des rêves de mort, de haine et de cruauté.

Je suis désolé, car je te croyais fidèle,
Tu ne peux désormais être celle
Qui a le devoir de guider mes pas,
Car tu me mèneras à mon trépas.

Alors, par les pouvoirs qui me sont accordés,
En regard des faits compromettant déjà cités:
Toi, Passion,
Est condamnée à l'exil sans possibilité de pardon.
Aujourd'hui, tu quittes mon âme, mon esprit,
Pour être remplacée par la logique et la raison
Qui reprendront le mandat de diriger ma vie
Et d'extraire de mon être, tout ton poison.
____
<<<
[verse]
____
Adieu,
Que la sentence soit exécutée, sous l'œil des Dieux.
Je n'oublierai jamais la porte que tu m'as ouverte
Sans avoir conscience que je courrais à ma perte.
Pendant un moment, la folie
A été la maîtresse de mon esprit.
____
