== Le souverain exilé

[verse]
____
Tu es là, remarquable,
Par ta démarche loufoque et ton allure médiocre.
Lorsque tu tentes d'être aimable,
Avec ceux qui te considèrent comme une attraction,
Une aberration,
Ils rient de toi, se moquent...
De ta démarche loufoque, et de ton allure médiocre.
Lorsque tu leur prodigues des conseils,
Les ignorants oublient que tu existes, perdent la piste,
Où ils te harcelaient, jadis.

Grand Roi de la conscience, de l'imaginaire,
Pourquoi n’utilises-tu pas  de tes pouvoirs extraordinaires
Pour à tout jamais les faire taire?
Le Grand Roi me fixe de ses yeux tristes,
Et me dit qu'il ne souhaite pas que ce soit ainsi que tout finisse.

Il s'en va, revêtant le manteau de l'indifférence,
Et, comme par une éternelle malchance,
Suscite les moqueries de ceux qui,
Dans leur cloaque venimeux,
Ne voient même pas la grandeur de cœur
De ce merveilleux souverain.

Va, mon ami, et que dans le monde, d'autres comme moi,
S'aperçoivent de ta chaleur
Et oublient de juger avec leurs yeux,
Ta démarche loufoque et ton allure médiocre.
____
