== Le souverain exilé

[verse]
____
Tu es là, remarquable,
Par ta démarche loufoque et ton allure médiocre.
Lorsque tu tentes d'être aimable,
Avec ceux qui te voient comme une attraction,
Une aberration,
Ils rient de toi, se moquent...
De ta démarche loufoque, de ton allure médiocre.
Lorsque tu leur prodigues des conseils,
Les ignorants oublient que tu existes,
Perdent la piste,
Où ils te harcelaient, jadis.

Grand Roi de la conscience, de l'imaginaire,
Pourquoi ne pas à jamais les faire taire
Avec tes pouvoirs extraordinaires?
Le Grand Roi me fixe de ses yeux tristes,
D'un long regard fataliste.

Il s'en va, revêtant la cape de l'indifférence,
Et, comme par une éternelle malchance,
Suscite les moqueries de ceux qui,
Dans leur cloaque venimeux,
Ne voient même pas la grandeur de cœur
De ce merveilleux souverain.
____
<<<
[verse]
____
Mon ami, va par le monde, que d'autres,
S'aperçoivent de ta chaleur
Et oublient de juger avec leurs yeux,
Ta démarche loufoque et ton allure médiocre.
____
