== Tanit

[verse]
____
C'était dans un rêve, ou bien un demi-sommeil,
Que j'aperçus tes lèvres vermeilles
Pour la première fois,
Belle déesse des Carthaginois.

Depuis cette vision, de ton corps voluptueux
Dans l'air frais et vaporeux
En un endroit immobile et mystérieux,
De tes bras tendus vers moi
Me découvrant tes attraits sous ta toge diaphane,
Je souhaite que jamais ton souvenir ne se fane.

Doucement, à l'oreille, tu m'as soufflée:
"Tout va bien, je suis arrivée."
Et alors, de cette terre ensommeillée
Jaillirent des étoiles enflammées
S'envolant vers le firmament,
Pour accompagner ton sourire éblouissant.
Je te disais que je t'aimais
Et des marécages bordés de vieux bosquets
Surgirent des sources d'eau claires et limpides
Semblable à tes rires timides.
Délicatement, tu me pris la main,
Puis, m'indiquas au loin
L'horizon où se préparait le lendemain,
Me montrant ainsi que de mon rêve, c'était la fin.
____
<<<
[verse]
____
Dès que nos merveilles
Disparurent au profit du soleil,
Maître de l'état de veille,
Tu m'embrassas et me dis, avant de me laisser:
"N'oublie pas, je suis fertilité et je puis tout créer."

Comme une brume s'évapore au vent,
Tu me quittas, tranquillement,
Chuchotant des paroles tendres
Pour que ta présence ne retourne pas aux cendres,
De ta ville splendide, maintenant désertée,
Où il n'y a plus personne pour t'adorer.
____
