== La vie d'une rose

[verse]
____
Fraîches comme la rosée,
Les premières feuilles de cette beauté
Venaient de percer la terre encore gelée.
Le soleil, roi du ciel,
L'appelait de sa lueur dorée,
Cette douce merveille
Ne pouvait que tenter de s'élever.

La rose, passionnée, se garnit bientôt d'épines
Pour que les autres plantes
Ne puissent lui faire courber l'échine
Si elles tentaient de paraître plus charmantes.
Elle voulait le soleil pour elle seule,
Qu'il lui réserve ses rayons les plus tendres
Pour réchauffer ses délicates feuilles.
Vers la terre, elle désirait ne jamais redescendre.

Les beaux jours étant arrivés,
Les fleurs de leurs plus beaux atours
Commencèrent à se parer
Pour attirer l'attention du soleil à leur tour.
La rose prépara bientôt de ses plus belles pétales
Sachant qu'avec de la volonté
Elle pourrait dérouter ses rivales
Afin de vivre un amour ardent, enflammé.
____
<<<
[verse]
____
Un matin, voyant le soleil se lever
Chassant la froide nuit,
Elle dévoila sa robe colorée
Et son parfum flotta jusqu'à lui.
Le soleil, émerveillé par tant de majesté,
Décida de donner à la rose tout son amour
Pour que son cœur soit continuellement réchauffé
Et que son arôme l'enivre toute la journée.

Plusieurs mois, les amoureux se cajolèrent
Produisant une valse d'odeurs et de lumières,
Que les autres fleurs
Ne pouvait qu'admirer avec langueur.
Malheureusement, la blanche dame
Froide et cruelle charma le soleil.
Elle masqua le regard de la rose,
Comme celui d'une personne qu'on condamne,
En emplissant le ciel de nuages.
La rose, avec désespoir,
Appela son amour avec ce qui lui restait de force.
Rien n'y changea, l'hiver s'installait,
Chassant les jours de gloire,
Balayant les champs avec un vent féroce.

La rose se flétrit, sa fin était proche.
Avant de toucher le sol figé comme la roche,
Elle laissa s'envoler sa dernière pétale
Dans l'air d'une froideur fatale.
Ainsi, elle espérait revivre, loin d'hier,
En un pays où il n'y aurait pas d'hiver.

La rose mourut avec l'espoir
Qu'un jour elle puisse enfin voir
Une terre où le bonheur ne serait pas éphémère.
Où, à l'amour, le temps n'est pas une frontière.
____
