== La vigie de Cartier

[verse]
____
De là-haut, je voyais les oiseaux,
Beaux ils étaient dans leurs blancs manteaux,
Plongeant et replongeant, si élégants
Qu'on aurait dit qu'ils étaient le vent.

Le vent du large s'était levé,
Chassant la calme nuit étoilée,
La veille de notre arrivée
En ces belles eaux bleutées,
Comme si le diable en ces vagues immenses
Tentait d'ébrécher notre confiance.

De là-haut, je voyais les oiseaux,
Beaux ils étaient dans leurs blancs manteaux,
Nous indiquant que nous n'étions plus loin
De cette nouvelle terre de demain.

Demain, la terre nous toucherons,
Un pays nous y bâtirons
Pour que nos enfants vivent debout, fiers,
Qu'ils prospèrent en cette lande hospitalière.

Une mince bande sombre, à peine visible à l'horizon,
Me tira de mes réflexions.
&#x00AB;Terre, messire Cartier, Terre!&#x00BB;,
Criais-je à mon capitaine, en-bas, sur le pont.
____
<<<
[verse]
____
Lorsque je relevais à nouveau les yeux
Je pus constater que ce n'était pas une chimère.
Ce pays, nous en poserons la première pierre.
____
