== Équinoxe

[verse]
____
Dans ma carcasse, autant qu'à sa surface,
Il me semble n'y avoir ni douleur, ni le moindre bonheur fugace.
C'est l'équinoxe en ce monde qui a vieilli trop vite:
Je n'ai plus peur de la triste nuit, je ne veux plus d'une lueur hypocrite.
En mon cœur, plus rien n'a de poids
C'est ainsi depuis que je vois l'être au fond de moi
Qui brandit les poings vers le ciel avec rage
Car, dans ma personnalité, il est en cage.

La nuit, le jour,
La vie, la mort,
La haine et l'amour,
Plus rien ne peut me faire du tort.
J'ai déjà été détruit par les larmes et les remords.
Aujourd'hui, je regrette d'avoir anéanti mon coeur
En voulant éviter la réalité, parce que j'avais peur.

Désormais, je ne veux plus regarder à l'intérieur de ce temple,
Bâti sur ce qui s'appelait sensibilité, pour constater qu'il est habité
Par un ange et un démon qui scrutent mon âme, la contemplent.
Malheureusement, l'ivresse passée, je constatais que mon temple était déserté,
Celui-ci retournant à l'état de la pierre que j'avais sculptée.
J'avais cru en l'amour, un instant, de toute mon âme.
Mais je ne croyais pas que mon cœur deviendrait si infâme.

Lorsque je regarde dans le miroir,
J'aperçois l'homme qui ne cesse de se dire qu'il n'y a plus d'espoir,
Qu'il n'y a plus de place pour la passion
En ce territoire sombre qu'est devenue ma raison.
La noirceur, ni la clarté, il ne veut rencontrer
Puisque l'indifférence lui sert à s’abriter.

Cependant, l'équinoxe me permet de garder l'équilibre,
De croire qu'il se peut de nouveau que mon âme vibre.
De mon âme, il ne reste plus rien à détruire,
Mais tout à reconstruire.
____
