== Équinoxe

[verse]
____
Dans ma carcasse, autant qu'à sa surface,
Il me semble n'y avoir ni douleur,
Ni le moindre bonheur fugace.
C'est l'équinoxe en ce monde qui a vieilli trop vite:
Je n'ai plus peur de la triste nuit,
Je ne veux plus d'une lueur hypocrite.
En mon cœur, plus rien n'a de poids
C'est ainsi depuis que je vois l'être au fond de moi
Qui brandit les poings vers le ciel avec rage
Car, dans ma personnalité, il est en cage.

La nuit, le jour,
La vie, la mort,
La haine et l'amour,
Plus rien ne peut me faire du tort.
J'ai déjà été détruit par les larmes et les remords.
Aujourd'hui, je regrette d'avoir anéanti mon cœur
En voulant éviter la réalité, parce que j'avais peur.

Désormais, je ne veux plus contempler ce temple,
Bâti sur ce qui s'appelait sensibilité,
Pour constater qu'il est habité
Par un ange et un démon qui scrutent mon âme,
La contemplent.



Malheureusement, l'ivresse passée,
Je constatais que mon temple était déserté,
Celui-ci retournant à l'état de la pierre
Que j'avais sculptée.
J'avais cru en l'amour, de toute mon âme.
Sans croire que mon cœur deviendrait si infâme.

Lorsque je regarde dans le miroir,
J'aperçois l'homme qui ne cesse de se dire
Qu'il n'y a plus d'espoir,
Qu'il n'y a plus de place pour la passion
En ce territoire sombre qu'est devenue ma raison.
La noirceur, ni la clarté, il ne veut rencontrer
Puisque l'indifférence lui sert à s’abriter.

L'équinoxe me permet de garder l'équilibre,
De croire qu'à nouveau mon être vibre.
De mon âme, il ne reste plus rien à détruire,
Mais tout à reconstruire.
____
